title: Estatus - Inmuebles Las Mercedes
baseURL: ""
languageCode: en
params:
  shortDateFormat: 15:04 â€” Enero 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Sitio Principal
      description: Sitio Principal Inmuebles Las Mercedes
      link: https://inmuebleslasmercedes.com
    - name: Helpdesk
      description: Our company customer support site
      link: https://support.example.com/
  dateFormat: Enero 2, 2006 a las 3:04 PM
  disqusShortname: null
  timezoneString: America/Caracas
  logo: /images/clearstatus.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    example.com' href='https://www.example.com/'>example</a> systems
    operations.<br />Follow us <a class='text-grey-darkest' title='Visit our
    page on Twitter' href='https://www.twitter.com/example'>on Twitter</a> or
    subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be
    alerted of new events.
  copyrightHolder: Inmuebles Las Mercedes.
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>Example.com</a> provides open-source
    software for all kind of sectors.
